### ISSUE TITLE
[Question] Support for runtime platform ARMv7

### ISSUE THREAD

**Issue by Noschvie** [olavgg/moinmoin-wiki#5]
How can we get the MoinMoin container running on this platform ?

`Linux raspberrypi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux`

Thanks

**Comment by olavgg** [comment]
Raspberry pi support shouldn't be that difficult, have you tried building the image yourself on Raspberry pi?

**Comment by olavgg** [comment]
armv7l is 32bits, I do have a Rasperry Pi 1 unit collecting dust, which will hopefully work for testing this.

**Comment by Noschvie** [comment]
Running the command

`docker build . -t moinmoin`

results in:

```
Step 21/35 : RUN rm /etc/nginx/sites-enabled/default
 ---> Using cache
 ---> aa8d538e2cf5
Step 22/35 : ADD generate_ssl_key.sh /usr/local/bin/
 ---> Using cache
 ---> c8a0ce6e9d92
Step 23/35 : RUN /usr/local/bin/generate_ssl_key.sh moinmoin.example.org
 ---> Running in 1fb0558c446c
/bin/sh: 1: /usr/local/bin/generate_ssl_key.sh: not found
The command '/bin/sh -c /usr/local/bin/generate_ssl_key.sh moinmoin.example.org' returned a non-zero code: 127
```

**Comment by olavgg** [comment]
That is weird, could it be that openssl is missing here?

Could you replace that line in the Dockerfile with this command instead
`openssl req -x509 -newkey rsa:4096 -sha256 -nodes -keyout key.pem -out cert.pem -subj "/CN=example.com" -days 3650`

**Comment by Noschvie** [comment]
```
pi@raspberrypi:~/MoinMoin $ openssl version
OpenSSL 1.1.1d  10 Sep 2019
```

Replacing the line as suggested results in successful building the container.

But starting results in:

`/usr/bin/env: 'sh\r': No such file or directory`

**Comment by olavgg** [comment]
Thank you for confirming that it works. This may be a bug in the ARM image of Debian, I will test this myself and do some investigation. Anyway refactoring the Docker build file with this change is a good fix. Thank you for your feedback.

**Comment by Noschvie** [comment]
... bilding the container works, but running the container fails with:

`/usr/bin/env: 'sh\r': No such file or directory`

Any idea or workaround ?
Thanks.

**Comment by olavgg** [comment]
Its the she bangs that fails, probably because the sh bin is not available the the `$PATH`
try replacing `#!/usr/bin/env sh` with `#!/bin/sh`

**Comment by olavgg** [comment]
in the start.sh file

**Comment by Noschvie** [comment]
replacing `#!/usr/bin/env sh` with `#!/bin/sh` in the start.sh file works !
Thanks
