### ISSUE TITLE
using a dump

### ISSUE THREAD

**Issue by arademaker** [olavgg/moinmoin-wiki#8]
I have a backup of an old installation of MoinMoin 1.9, how can I use it to start the container? My backup has the following structure:

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/86403/116632219-03f5e080-a92d-11eb-924a-e992e57aada6.png">

**Comment by olavgg** [comment]
Try:

sudo docker run -d -p 443:443 -p 80:80 -v /Users/ar/hpsg/documentation/docs/moin/ltg/moin/delphin/data --name my_wiki olavgg/moinmoin-wiki
